### PR TITLE
Did a bunch of shit

### PR DESCRIPTION
**Pull request by MemeHoovy**
I added the ghost tapping system levi

### CODE REVIEW

**Comment by LEVIXDDLMAO** [comment]
if i miss a note with it still count as a miss?

**Comment by MemeHoovy** [comment]
yes

**Comment by LEVIXDDLMAO** [comment]
why did you remove zoom stages are broken

**Comment by MemeHoovy** [comment]
> why did you remove zoom stages are broken

it's not in flixel 5

**Comment by LEVIXDDLMAO** [comment]
okay? but stages are broken and the game is unplayable

**Comment by MemeHoovy** [comment]
uhhh, idk

**Comment by LEVIXDDLMAO** [comment]
im adding zoom back ( use flixel 4.11.0 )

**Comment by MemeHoovy** [comment]
alright

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by MemeHoovy** [comment]
I can't think straight right now

**Comment by LEVIXDDLMAO** [comment]
can you do the miss counter?

**Comment by LEVIXDDLMAO** [comment]
and the combo doesn't restart when missing

**Comment by MemeHoovy** [comment]
> can you do the miss counter?

alright

**Comment by LEVIXDDLMAO** [comment]
:D

**Comment by MemeHoovy** [comment]
but, it's the last thing I do before I go to bed though

**Comment by LEVIXDDLMAO** [comment]
k

**Comment by LEVIXDDLMAO** [comment]
:D

**Pull request merged**
